default: &default                                                                                                                                                                                                                              
  adapter: postgresql
  pool: 5
  timeout: 5000
  
development:
  <<: *default
  database: boiler_development
 
test:
  <<: *default
  database: boilder_test
 
production:
  <<: *default
  database: boiler_production
  host:     <%= ENV['POSTGRES_CONTAINER'] %>  
  username: <%= ENV['POSTGRES_USER'] %>  
  password: <%= ENV['POSTGRES_PASSWORD'] %>  

